"""The console shell: one nav frame across every web surface (console.py).

The surfaces used to be five unrelated documents at three path prefixes with no
links between them — using any of them meant already knowing its URL. These
tests pin the properties that make the frame work: relative links (so a static
file generated by the harvester, which never sees the bearer token, still links
correctly), one source of truth for the IA, and a retrofit that degrades to
"no nav" rather than to a corrupted page.
"""
import os
import unittest
from importlib.util import find_spec
from unittest.mock import patch

os.environ.setdefault("OAUTH_SIGNING_KEY", "test-signing-key-not-a-real-secret")
os.environ.setdefault("OAUTH_PASSWORD", "test-password")
os.environ.setdefault("MCP_BEARER_TOKEN", "testtoken")

if find_spec("psycopg_pool") and find_spec("mcp"):
    from mcp_server.api import console, console_pages
else:
    console = console_pages = None


@unittest.skipIf(console is None, "server deps not installed")
class NavTests(unittest.TestCase):
    def test_every_link_is_relative(self):
        # Absolute links would need the bearer token, which the harvester-side
        # generators never see. This is what makes the retrofit possible at all.
        for _key, href, _label, _purpose in console.NAV:
            self.assertTrue(href.startswith("./"), f"{href} is not relative")

    def test_active_page_is_marked_for_styling_and_a11y(self):
        html = console.nav_html("graph")
        self.assertIn('aria-current="page"', html)
        # exactly one current page
        self.assertEqual(html.count('aria-current="page"'), 1)

    def test_every_nav_entry_renders(self):
        html = console.nav_html("home")
        for _key, _href, label, _purpose in console.NAV:
            self.assertIn(label, html)

    def test_shell_paints_its_own_background(self):
        # An artifact/page that leaves body transparent borrows the host ground
        # and can render one theme's text on the other theme's surface.
        html = console.shell("t", "home", "<p>x</p>")
        self.assertIn("background:var(--paper)", html.replace(" ", ""))

    def test_shell_defines_both_themes(self):
        html = console.shell("t", "home", "")
        self.assertIn("prefers-color-scheme:dark", html)
        self.assertIn('[data-theme="dark"]', html)


@unittest.skipIf(console is None, "server deps not installed")
class InjectNavTests(unittest.TestCase):
    def test_nav_is_spliced_after_body(self):
        out = console.inject_nav("<html><body><h1>Flow</h1></body></html>", "flow")
        self.assertIn("atx-nav", out)
        self.assertLess(out.index("atx-nav"), out.index("<h1>"))

    def test_body_with_attributes_still_matches(self):
        out = console.inject_nav('<html><body class="x" id="y">hi</body></html>', "flow")
        self.assertIn("atx-nav", out)
        # not spliced into the middle of the tag
        self.assertNotIn('<body class="x" id="y"<', out)

    def test_a_document_without_a_body_is_returned_unchanged(self):
        # Degrade to "no nav", never to a corrupted page.
        src = "not really html"
        self.assertEqual(console.inject_nav(src, "flow"), src)

    def test_injected_page_marks_the_active_surface(self):
        out = console.inject_nav("<html><body>x</body></html>", "tickers")
        self.assertIn('aria-current="page"', out)


@unittest.skipIf(console is None, "server deps not installed")
class ConsolePageTests(unittest.TestCase):
    def test_overview_survives_an_unreachable_database(self):
        # A console that 500s when Postgres blinks is worse than one that says so.
        with patch.object(console_pages.db_v2, "query_data_status",
                          side_effect=RuntimeError("down")):
            html = console_pages.overview_html(12)
        self.assertIn("unreachable", html)
        self.assertIn("atx-nav", html)          # still navigable

    def test_overview_reports_pipeline_state(self):
        rows = [{"table_name": "raw_twse_t86", "row_count": 1200, "latest_date": "2026-08-11"}]
        with patch.object(console_pages.db_v2, "query_data_status", return_value=rows):
            html = console_pages.overview_html(7)
        self.assertIn("raw_twse_t86", html)
        self.assertIn("2026-08-11", html)
        self.assertIn("1,200", html)

    def test_system_map_groups_the_live_registry(self):
        # Built from the registry, so it cannot drift the way a hand-kept list
        # does — which is exactly how sc_capabilities silently lost 15 tools.
        html = console_pages.system_map_html(
            ["q_valuation", "rg_status", "sc_ticker_momentum", "ticker_lookup"])
        for name in ("q_valuation", "rg_status", "sc_ticker_momentum", "ticker_lookup"):
            self.assertIn(name, html)
        self.assertIn("4 MCP tools", html)

    def test_system_map_omits_families_with_no_tools(self):
        html = console_pages.system_map_html(["q_valuation"])
        self.assertIn("q_", html)
        self.assertNotIn("Risk Guard: the market risk light", html)


if __name__ == "__main__":
    unittest.main()
