"""The console shell: one nav frame across every web surface (console.py).

The surfaces used to be five unrelated documents at three path prefixes with no
links between them — using any of them meant already knowing its URL. These
tests pin the properties that make the frame work: relative links (so a static
file generated by the harvester, which never sees the bearer token, still links
correctly), one source of truth for the IA, and a retrofit that degrades to
"no nav" rather than to a corrupted page.
"""
import os
import unittest
from importlib.util import find_spec

os.environ.setdefault("OAUTH_SIGNING_KEY", "test-signing-key-not-a-real-secret")
os.environ.setdefault("OAUTH_PASSWORD", "test-password")
os.environ.setdefault("MCP_BEARER_TOKEN", "testtoken")

if find_spec("psycopg_pool") and find_spec("mcp"):
    from mcp_server.api import console, console_pages
else:
    console = console_pages = None


@unittest.skipIf(console is None, "server deps not installed")
class NavTests(unittest.TestCase):
    def test_every_link_is_relative(self):
        # Absolute links would need the bearer token, which the harvester-side
        # generators never see. This is what makes the retrofit possible at all.
        for _key, href, _label, _purpose in console.NAV:
            self.assertTrue(href.startswith("./"), f"{href} is not relative")

    def test_active_page_is_marked_for_styling_and_a11y(self):
        html = console.nav_html("graph")
        self.assertIn('aria-current="page"', html)
        # exactly one current page
        self.assertEqual(html.count('aria-current="page"'), 1)

    def test_every_nav_entry_renders(self):
        html = console.nav_html("home")
        for _key, _href, label, _purpose in console.NAV:
            self.assertIn(label, html)

    def test_shell_paints_its_own_background(self):
        # An artifact/page that leaves body transparent borrows the host ground
        # and can render one theme's text on the other theme's surface.
        html = console.shell("t", "home", "<p>x</p>")
        self.assertIn("background:var(--paper)", html.replace(" ", ""))

    def test_shell_defines_both_themes(self):
        html = console.shell("t", "home", "")
        self.assertIn("prefers-color-scheme:dark", html)
        self.assertIn('[data-theme="dark"]', html)


@unittest.skipIf(console is None, "server deps not installed")
class InjectNavTests(unittest.TestCase):
    def test_nav_is_spliced_after_body(self):
        out = console.inject_nav("<html><body><h1>Flow</h1></body></html>", "flow")
        self.assertIn("atx-nav", out)
        self.assertLess(out.index("atx-nav"), out.index("<h1>"))

    def test_body_with_attributes_still_matches(self):
        out = console.inject_nav('<html><body class="x" id="y">hi</body></html>', "flow")
        self.assertIn("atx-nav", out)
        # not spliced into the middle of the tag
        self.assertNotIn('<body class="x" id="y"<', out)

    def test_a_document_without_a_body_is_returned_unchanged(self):
        # Degrade to "no nav", never to a corrupted page.
        src = "not really html"
        self.assertEqual(console.inject_nav(src, "flow"), src)

    def test_injected_page_marks_the_active_surface(self):
        out = console.inject_nav("<html><body>x</body></html>", "tickers")
        self.assertIn('aria-current="page"', out)


@unittest.skipIf(console is None, "server deps not installed")
class ConsolePageTests(unittest.TestCase):
    # Overview and market page behaviour moved to tests/test_console_pages.py,
    # which fixtures the REAL return shapes. The tests that lived here mocked
    # query_data_status as a list of rows; it returns a single dict, so they
    # passed while /d/<token>/ raised AttributeError on every production request.

    def test_system_map_groups_the_live_registry(self):
        # Built from the registry, so it cannot drift the way a hand-kept list
        # does — which is exactly how sc_capabilities silently lost 15 tools.
        html = console_pages.system_map_html(
            ["q_valuation", "rg_status", "sc_ticker_momentum", "ticker_lookup"])
        for name in ("q_valuation", "rg_status", "sc_ticker_momentum", "ticker_lookup"):
            self.assertIn(name, html)
        self.assertIn("4 MCP tools", html)

    def test_system_map_omits_families_with_no_tools(self):
        html = console_pages.system_map_html(["q_valuation"])
        self.assertIn("q_", html)
        self.assertNotIn("Risk Guard: the market risk light", html)


if __name__ == "__main__":
    unittest.main()


class TestTickersDegradesInsteadOf503:
    """The Tickers page must not 500/503 when Postgres is down.

    Overview and Market already degrade to a rendered page. Tickers raised a
    bare `HTTPException(503)`, so with the database down the console's own nav
    link led to an unstyled error with no way back -- at exactly the moment an
    operator opens the console to find out what is wrong.
    """

    @staticmethod
    def _boom():
        raise RuntimeError("pool timeout")

    def test_console_context_renders_with_nav(self, monkeypatch):
        import graph_view
        monkeypatch.setattr(graph_view, "_ticker_directory", self._boom)

        resp = graph_view.get_tickers_html("tok", nav="tickers")
        body = resp.body.decode()

        assert resp.status_code == 200
        assert "unavailable" in body
        # The console frame, so the operator can still reach Overview.
        assert "Overview" in body
        # NAV links stay relative -- absolute ones break under the token prefix.
        assert 'href="/d/tok/market"' not in body

    def test_legacy_context_does_not_use_relative_console_nav(self, monkeypatch):
        """`/t/<token>/` is a different prefix, so relative NAV links would 404.

        This is the trap that makes the two shapes necessary rather than
        cosmetic: `./market` under /t/<token>/ resolves to /t/<token>/market.
        """
        import graph_view
        monkeypatch.setattr(graph_view, "_ticker_directory", self._boom)

        body = graph_view.get_tickers_html("tok", nav="").body.decode()

        assert "unavailable" in body
        assert './market' not in body
        assert '/d/tok/' in body          # points back at the console absolutely

    def test_route_returns_200_not_503(self, monkeypatch):
        """End-to-end through the ASGI app, which is where the 503 showed up."""
        import graph_view
        import index
        from starlette.testclient import TestClient

        monkeypatch.setattr(graph_view, "_ticker_directory", self._boom)
        monkeypatch.setattr(index, "MCP_BEARER_TOKEN", "tok")

        r = TestClient(index.app).get("/d/tok/tickers")
        assert r.status_code == 200, f"regressed to {r.status_code}"
        assert "unavailable" in r.text
