"""Correlation-network graph viewer.

The 4-panel matplotlib PNG and HTML wrapper are generated by
`python -m src.quant.correlation_snapshot`. We just serve the files.

Endpoints (mounted under /g/{TOKEN}/):
  GET /g/{TOKEN}/             → HTML page wrapping the PNG
  GET /g/{TOKEN}/graph.png    → raw PNG (direct image, Telegram-friendly)
  GET /g/{TOKEN}/data.json    → snapshot JSON (for programmatic access)
"""
from __future__ import annotations

import json
from pathlib import Path

from fastapi import HTTPException
from fastapi.responses import HTMLResponse, JSONResponse, Response

_STATIC = Path(__file__).parent / "static"
_HTML_PATH      = _STATIC / "graph.html"
_PNG_PATH       = _STATIC / "graph.png"
_JSON_PATH      = _STATIC / "graph_snapshot.json"
_DASHBOARD_PATH = _STATIC / "dashboard.html"


def get_viewer_html() -> HTMLResponse:
    if not _HTML_PATH.exists():
        raise HTTPException(503, "graph.html not yet generated; "
                                 "run `python -m src.quant.correlation_snapshot`")
    return HTMLResponse(content=_HTML_PATH.read_text())


def get_graph_png() -> Response:
    if not _PNG_PATH.exists():
        raise HTTPException(503, "graph.png not yet generated")
    return Response(content=_PNG_PATH.read_bytes(), media_type="image/png")


def get_snapshot_json() -> JSONResponse:
    if not _JSON_PATH.exists():
        raise HTTPException(503, "snapshot not yet generated")
    return JSONResponse(content=json.loads(_JSON_PATH.read_text()))


def get_dashboard_html() -> HTMLResponse:
    if not _DASHBOARD_PATH.exists():
        raise HTTPException(503, "dashboard.html not yet generated; "
                                 "run `python -m src.dashboard.build`")
    return HTMLResponse(content=_DASHBOARD_PATH.read_text())
